# Generated by Django 4.1.7 on 2023-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="teacher",),
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(related_name="students", to="school.teacher"),
        ),
    ]
